### ISSUE TITLE
Build on github.io page failed

### ISSUE THREAD

**Issue by minhphan03** [DavideBri/Gesko#32]
**Describe the bug**
I pushed a copy of the repo to my github.io one to see if it works properly before customizing it but it seems like the build is failed while installing gems from Ruby store (Screenshot from GitHub Actions page). I went to the store to see if those versions existed, and they were, so maybe the problem stemmed from the platforms?

Platforms copied from Gemfile.lock (unmodified):
-  arm64-darwin-22
- x64-mingw32
- x86_64-linux

<img width="1105" alt="Screenshot 2023-08-20 at 12 15 29 AM" src="https://github.com/DavideBri/Gesko/assets/66846878/1385f8b1-66e4-4073-8725-6ab883fb03b3">

It built just fine locally, just to let you know.

Operating system: macOS 13.0 Ventura

**Comment by DavideBri** [comment]
Thanks @minhphan03 for opening an issue about it!
You mentioned that you tested the build locally and it worked fine, which indicates that the issue might be specific to the GitHub Actions environment.
Turns out that the third party Github Action I was using was outdated. In the last [commit](https://github.com/DavideBri/Gesko/commit/a6a4a1d05a2d914ab6afd8125187dd9fcd5496a7?diff=unified#diff-60ac246cc02819dea1007076ba57241caa7c7d1e8232a5179124d4e63bb366f8) i update the `.github/workflow/jejyll.yml` to a new mantained one.
I tested and now seem to work just fine! 

Thanks again and happy weekend!
- Dav
